#!/bin/bash

ROOT_DIR=$(cd `dirname $0`; cd ..; pwd)

if test -e $ROOT_DIR/.git
then
    rm -rf $ROOT_DIR/.git
fi

if test -x "/usr/local/bin/inspect-commits"
then
    rm /usr/local/bin/inspect-commits
fi

ln -s $ROOT_DIR/release/inspect-commits /usr/local/bin/inspect-commits
